apiVersion: v1
kind: Service
metadata:
  name: flask-hello-world-service
  namespace: kube-mlops
spec:
  selector:
    app: flask-hello-world
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30010
  type: NodePort
